### PR TITLE
Plots related to profiling the objective

### PR DESCRIPTION
**Pull request by dmbates**
- these plots require the `profile` branch of the `MixedModels` repository
- functions include `zetaplot` and a `profiledensity` plot
- I added a dependency on `BSplineKit` to facilitate testing of this code. Let me know if you (Phillip) prefer not to have this dependency.
- some sample code is given below.

### CODE REVIEW

**Comment by dmbates** [comment]
Tests are currently failing because I haven't forced using the profile branch of MixedModels resulting in `MixedModelsProfile` being undefined.

If the profile branch of MixedModels is used plots such as
```julia
using CairoMakie, MixedModels, MixedModelsMakie

include(pkgdir(MixedModels, "test", "modelcache.jl"))
CairoMakie.activate!(; type="svg")
pr01 = profile(only(models(:dyestuff)));
zetaplot(pr01)  # default intervals are at 50%, 80%, 90%, 95% and 99% coverage
confint(pr01)    # default is 95% coverage
profiledensity(pr01)  # the density functions that would produce these profiles
```
should work.

**Comment by dmbates** [comment]
> @dmbates if I try the example but with `last(models(:kb07))`, then it fails at the profiling step. It does work with the first two kb07 models.

@palday  Thanks for catching that.  I can reproduce the failure and will look into it.  I suspect that what is happening is that the forward spline mapping a beta component to zeta can be constructed but the reverse spline can't because the slope becomes too steep.  When I was creating profiles for parameters in nonlinear regression models I had to define a "spline-like" interpolation for the reverse direction consisting of polynomial segments that matched the position and slope of the forward spline at the knot positions.

This will probably need to be addressed in the MixedModels.jl/src/profile.jl code, not in this package.

**Comment by dmbates** [comment]
@palday Turns out the problem is in `MixedModels.profileσ`.  I need to look in more depth but you can see that things are rather peculiar in a plot of `ζ` versus `σ` for `MixedModels.profileσ(last(models(:kb07)))`

**Comment by dmbates** [comment]
@palday See the last commit in https://github.com/JuliaStats/MixedModels.jl/pull/639.  These horribly over-parameterized models can be sensitive to starting estimates.  In `profileσ` I set optsum.initial for the constrained optimization to the final value from the general optimization but moving the components on the boundary slightly off the boundary.

**Comment by palday** [comment]
@dmbates I've updated documentation, changed to the new MixedModels release, and added tests. Are we missing anything here in your opinion?

**Comment by dmbates** [comment]
Looks good.  Thanks for making all those fixes.  Feel free to merge this whenever you like.

**Review by palday — APPROVED** [review]

**Pull request merged**
