### PR TITLE
Patch release for Makie compat bump

### PR DESCRIPTION
**Pull request by palday**

### CODE REVIEW

**Review by dmbates — COMMENTED** [review]
I'm not sure I understand how this change is to work.  It seems that it is just bumping the version number without any other changes.  Will that be enough to resolve the dependencies in other packages?  (I suppose I could always check this myself, which I will do.)

**Comment by palday** [comment]
@dmbates yes -- because the last release didn't include the Makie 0.15 in the compat.

**Comment by palday** [comment]
(The extra compat was added without tagging a release.)

**Review by dmbates — APPROVED** [review]
Thanks for the explanation.

**Pull request merged**
